# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ECommerce' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'IQKeyboardManager'
    pod 'RMessage'
    pod 'SVProgressHUD'
    pod 'CarbonKit'
    pod 'AFNetworking', '~> 3.0'
    pod 'JSONModel'
    pod 'SDWebImage', '~> 4.0'
    pod 'JVFloatLabeledTextField'
    pod 'PKYStepper', '0.0.1'
    pod 'PayPal-iOS-SDK'
    pod 'FBSDKLoginKit'
  # Pods for ECommerce

end
